[package]
name = "twitter-media-archiver"
version = "0.1.0"
authors = ["lae <lae@lae.is>"]

[dependencies]
clap = "~2.32.0"
failure = "~0.1"
failure_derive = "~0.1"
glob = "~0.2.0"
serde_json = "~1.0.0"
